
gdi_fns = [
    {'ord': '1', 'convention': 'pascal', 'ret': 'void', 'fn': 'SetBkColor', 'args': ['word', 'long']},
    {'ord': '2', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetBkMode', 'args': ['word', 'word']},
    {'ord': '3', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetMapMode', 'args': ['word', 'word']},
    {'ord': '4', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetROP2', 'args': ['word', 'word']},
    {'ord': '5', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetRelAbs', 'args': ['word', 'word']},
    {'ord': '6', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetPolyFillMode', 'args': ['word', 'word']},
    {'ord': '7', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetStretchBltMode', 'args': ['word', 'word']},
    {'ord': '8', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetTextCharacterExtra', 'args': ['word', 's_word']},
    {'ord': '9', 'convention': 'pascal', 'ret': 'void', 'fn': 'SetTextColor', 'args': ['word', 'long']},
    {'ord': '10', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetTextJustification', 'args': ['word', 's_word', 's_word']},
    {'ord': '11', 'convention': 'pascal', 'ret': 'void', 'fn': 'SetWindowOrg', 'args': ['word', 's_word', 's_word']},
    {'ord': '12', 'convention': 'pascal', 'ret': 'void', 'fn': 'SetWindowExt', 'args': ['word', 's_word', 's_word']},
    {'ord': '13', 'convention': 'pascal', 'ret': 'void', 'fn': 'SetViewportOrg', 'args': ['word', 's_word', 's_word']},
    {'ord': '14', 'convention': 'pascal', 'ret': 'void', 'fn': 'SetViewportExt', 'args': ['word', 's_word', 's_word']},
    {'ord': '15', 'convention': 'pascal', 'ret': 'void', 'fn': 'OffsetWindowOrg', 'args': ['word', 's_word', 's_word']},
    {'ord': '16', 'convention': 'pascal', 'ret': 'void', 'fn': 'ScaleWindowExt', 'args': ['word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '17', 'convention': 'pascal', 'ret': 'void', 'fn': 'OffsetViewportOrg', 'args': ['word', 's_word', 's_word']},
    {'ord': '18', 'convention': 'pascal', 'ret': 'void', 'fn': 'ScaleViewportExt', 'args': ['word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '19', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'LineTo', 'args': ['word', 's_word', 's_word']},
    {'ord': '20', 'convention': 'pascal', 'ret': 'void', 'fn': 'MoveTo', 'args': ['word', 's_word', 's_word']},
    {'ord': '21', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'ExcludeClipRect', 'args': ['word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '22', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'IntersectClipRect', 'args': ['word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '23', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'Arc', 'args': ['word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '24', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'Ellipse', 'args': ['word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '25', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'FloodFill', 'args': ['word', 's_word', 's_word', 'long']},
    {'ord': '26', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'Pie', 'args': ['word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '27', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'Rectangle', 'args': ['word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '28', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'RoundRect', 'args': ['word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '29', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'PatBlt', 'args': ['word', 's_word', 's_word', 's_word', 's_word', 'long']},
    {'ord': '30', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SaveDC', 'args': ['word']},
    {'ord': '31', 'convention': 'pascal', 'ret': 'void', 'fn': 'SetPixel', 'args': ['word', 's_word', 's_word', 'long']},
    {'ord': '32', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'OffsetClipRgn', 'args': ['word', 's_word', 's_word']},
    {'ord': '33', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'TextOut', 'args': ['word', 's_word', 's_word', 'str', 'word']},
    {'ord': '34', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BitBlt', 'args': ['word', 's_word', 's_word', 's_word', 's_word', 'word', 's_word', 's_word', 'long']},
    {'ord': '35', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'StretchBlt', 'args': ['word', 's_word', 's_word', 's_word', 's_word', 'word', 's_word', 's_word', 's_word', 's_word', 'long']},
    {'ord': '36', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'Polygon', 'args': ['word', 'ptr', 'word']},
    {'ord': '37', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'Polyline', 'args': ['word', 'ptr', 'word']},
    {'ord': '38', 'convention': 'pascal', 'ret': 'void', 'fn': 'Escape', 'args': ['word', 'word', 'word', 'segptr', 'ptr']},
    {'ord': '39', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'RestoreDC', 'args': ['word', 's_word']},
    {'ord': '40', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'FillRgn', 'args': ['word', 'word', 'word']},
    {'ord': '41', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'FrameRgn', 'args': ['word', 'word', 'word', 'word', 'word']},
    {'ord': '42', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'InvertRgn', 'args': ['word', 'word']},
    {'ord': '43', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'PaintRgn', 'args': ['word', 'word']},
    {'ord': '44', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SelectClipRgn', 'args': ['word', 'word']},
    {'ord': '45', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SelectObject', 'args': ['word', 'word']},
    {'ord': '47', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CombineRgn', 'args': ['word', 'word', 'word', 's_word']},
    {'ord': '48', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateBitmap', 'args': ['word', 'word', 'word', 'word', 'ptr']},
    {'ord': '49', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateBitmapIndirect', 'args': ['ptr']},
    {'ord': '50', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateBrushIndirect', 'args': ['ptr']},
    {'ord': '51', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateCompatibleBitmap', 'args': ['word', 'word', 'word']},
    {'ord': '52', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateCompatibleDC', 'args': ['word']},
    {'ord': '53', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateDC', 'args': ['str', 'str', 'str', 'ptr']},
    {'ord': '54', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateEllipticRgn', 'args': ['s_word', 's_word', 's_word', 's_word']},
    {'ord': '55', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateEllipticRgnIndirect', 'args': ['ptr']},
    {'ord': '56', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateFont', 'args': ['s_word', 's_word', 's_word', 's_word', 's_word', 'word', 'word', 'word', 'word', 'word', 'word', 'word', 'word', 'str']},
    {'ord': '57', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateFontIndirect', 'args': ['ptr']},
    {'ord': '58', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateHatchBrush', 'args': ['word', 'long']},
    {'ord': '60', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreatePatternBrush', 'args': ['word']},
    {'ord': '61', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreatePen', 'args': ['s_word', 's_word', 'long']},
    {'ord': '62', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreatePenIndirect', 'args': ['ptr']},
    {'ord': '63', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreatePolygonRgn', 'args': ['ptr', 'word', 'word']},
    {'ord': '64', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateRectRgn', 'args': ['s_word', 's_word', 's_word', 's_word']},
    {'ord': '65', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateRectRgnIndirect', 'args': ['ptr']},
    {'ord': '66', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateSolidBrush', 'args': ['long']},
    {'ord': '67', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'DPtoLP', 'args': ['word', 'ptr', 's_word']},
    {'ord': '68', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'DeleteDC', 'args': ['word']},
    {'ord': '69', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'DeleteObject', 'args': ['word']},
    {'ord': '70', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EnumFonts', 'args': ['word', 'str', 'segptr', 'long']},
    {'ord': '71', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EnumObjects', 'args': ['word', 'word', 'segptr', 'long']},
    {'ord': '72', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EqualRgn', 'args': ['word', 'word']},
    {'ord': '73', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'ExcludeVisRect', 'args': ['word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '74', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetBitmapBits', 'args': ['word', 'long', 'ptr']},
    {'ord': '75', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetBkColor', 'args': ['word']},
    {'ord': '76', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetBkMode', 'args': ['word']},
    {'ord': '77', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetClipBox', 'args': ['word', 'ptr']},
    {'ord': '78', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetCurrentPosition', 'args': ['word']},
    {'ord': '79', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetDCOrg', 'args': ['word']},
    {'ord': '80', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetDeviceCaps', 'args': ['word', 's_word']},
    {'ord': '81', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetMapMode', 'args': ['word']},
    {'ord': '82', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetObject', 'args': ['word', 's_word', 'ptr']},
    {'ord': '83', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetPixel', 'args': ['word', 's_word', 's_word']},
    {'ord': '84', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetPolyFillMode', 'args': ['word']},
    {'ord': '85', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetROP2', 'args': ['word']},
    {'ord': '86', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetRelAbs', 'args': ['word']},
    {'ord': '87', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetStockObject', 'args': ['word']},
    {'ord': '88', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetStretchBltMode', 'args': ['word']},
    {'ord': '89', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetTextCharacterExtra', 'args': ['word']},
    {'ord': '90', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetTextColor', 'args': ['word']},
    {'ord': '91', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetTextExtent', 'args': ['word', 'ptr', 's_word']},
    {'ord': '92', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetTextFace', 'args': ['word', 's_word', 'ptr']},
    {'ord': '93', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetTextMetrics', 'args': ['word', 'ptr']},
    {'ord': '94', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetViewportExt', 'args': ['word']},
    {'ord': '95', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetViewportOrg', 'args': ['word']},
    {'ord': '96', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetWindowExt', 'args': ['word']},
    {'ord': '97', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetWindowOrg', 'args': ['word']},
    {'ord': '98', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'IntersectVisRect', 'args': ['word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '99', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'LPtoDP', 'args': ['word', 'ptr', 's_word']},
    {'ord': '100', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'LineDDA', 'args': ['s_word', 's_word', 's_word', 's_word', 'segptr', 'long']},
    {'ord': '101', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'OffsetRgn', 'args': ['word', 's_word', 's_word']},
    {'ord': '102', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'OffsetVisRgn', 'args': ['word', 's_word', 's_word']},
    {'ord': '103', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'PtVisible', 'args': ['word', 's_word', 's_word']},
    {'ord': '104', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'RectVisibleOld', 'args': ['word', 'ptr']},
    {'ord': '105', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SelectVisRgn', 'args': ['word', 'word']},
    {'ord': '106', 'convention': 'pascal', 'ret': 'void', 'fn': 'SetBitmapBits', 'args': ['word', 'long', 'ptr']},
    {'ord': '117', 'convention': 'pascal', 'ret': 'void', 'fn': 'SetDCOrg', 'args': ['word', 's_word', 's_word']},
    {'ord': '119', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'AddFontResource', 'args': ['str']},
    {'ord': '121', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'Death', 'args': ['word']},
    {'ord': '122', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'Resurrection', 'args': ['word', 'word', 'word', 'word', 'word', 'word', 'word']},
    {'ord': '123', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'PlayMetaFile', 'args': ['word', 'word']},
    {'ord': '124', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetMetaFile', 'args': ['str']},
    {'ord': '125', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateMetaFile', 'args': ['str']},
    {'ord': '126', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CloseMetaFile', 'args': ['word']},
    {'ord': '127', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'DeleteMetaFile', 'args': ['word']},
    {'ord': '128', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'MulDiv', 'args': ['s_word', 's_word', 's_word']},
    {'ord': '129', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SaveVisRgn', 'args': ['word']},
    {'ord': '130', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'RestoreVisRgn', 'args': ['word']},
    {'ord': '131', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'InquireVisRgn', 'args': ['word']},
    {'ord': '132', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetEnvironment', 'args': ['str', 'str', 'word']},
    {'ord': '133', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetEnvironment', 'args': ['str', 'str', 'word']},
    {'ord': '134', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetRgnBox', 'args': ['word', 'ptr']},
    {'ord': '136', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'RemoveFontResource', 'args': ['str']},
    {'ord': '148', 'convention': 'pascal', 'ret': 'void', 'fn': 'SetBrushOrg', 'args': ['word', 's_word', 's_word']},
    {'ord': '149', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetBrushOrg', 'args': ['word']},
    {'ord': '150', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'UnrealizeObject', 'args': ['word']},
    {'ord': '151', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CopyMetaFile', 'args': ['word', 'str']},
    {'ord': '153', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateIC', 'args': ['str', 'str', 'str', 'ptr']},
    {'ord': '154', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetNearestColor', 'args': ['word', 'long']},
    {'ord': '155', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'QueryAbort', 'args': ['word', 'word']},
    {'ord': '156', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateDiscardableBitmap', 'args': ['word', 'word', 'word']},
    {'ord': '159', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetMetaFileBits', 'args': ['word']},
    {'ord': '160', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetMetaFileBits', 'args': ['word']},
    {'ord': '161', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'PtInRegion', 'args': ['word', 's_word', 's_word']},
    {'ord': '162', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetBitmapDimension', 'args': ['word']},
    {'ord': '163', 'convention': 'pascal', 'ret': 'void', 'fn': 'SetBitmapDimension', 'args': ['word', 's_word', 's_word']},
    {'ord': '172', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetRectRgn', 'args': ['word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '173', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetClipRgn', 'args': ['word']},
    {'ord': '175', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EnumMetaFile', 'args': ['word', 'word', 'segptr', 'long']},
    {'ord': '176', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'PlayMetaFileRecord', 'args': ['word', 'ptr', 'ptr', 'word']},
    {'ord': '179', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetDCState', 'args': ['word']},
    {'ord': '180', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetDCState', 'args': ['word', 'word']},
    {'ord': '181', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'RectInRegionOld', 'args': ['word', 'ptr']},
    {'ord': '190', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetDCHook', 'args': ['word', 'segptr', 'long']},
    {'ord': '191', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetDCHook', 'args': ['word', 'ptr']},
    {'ord': '192', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetHookFlags', 'args': ['word', 'word']},
    {'ord': '193', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetBoundsRect', 'args': ['word', 'ptr', 'word']},
    {'ord': '194', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetBoundsRect', 'args': ['word', 'ptr', 'word']},
    {'ord': '196', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetMetaFileBitsBetter', 'args': ['word']},
    {'ord': '230', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreatePQ', 'args': ['word']},
    {'ord': '231', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'MinPQ', 'args': ['word']},
    {'ord': '232', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'ExtractPQ', 'args': ['word']},
    {'ord': '233', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'InsertPQ', 'args': ['word', 'word', 'word']},
    {'ord': '234', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SizePQ', 'args': ['word', 'word']},
    {'ord': '235', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'DeletePQ', 'args': ['word']},
    {'ord': '240', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'OpenJob', 'args': ['str', 'str', 'word']},
    {'ord': '241', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'WriteSpool', 'args': ['word', 'ptr', 'word']},
    {'ord': '242', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'WriteDialog', 'args': ['word', 'str', 'word']},
    {'ord': '243', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CloseJob', 'args': ['word']},
    {'ord': '244', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'DeleteJob', 'args': ['word', 'word']},
    {'ord': '245', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetSpoolJob', 'args': ['word', 'ptr']},
    {'ord': '246', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'StartSpoolPage', 'args': ['word']},
    {'ord': '247', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EndSpoolPage', 'args': ['word']},
    {'ord': '250', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'Copy', 'args': ['ptr', 'ptr', 'word']},
    {'ord': '281', 'convention': 'pascal', 'ret': 'void', 'fn': 'DrvSetPrinterData', 'args': ['str', 'str', 'long', 'ptr', 'long']},
    {'ord': '282', 'convention': 'pascal', 'ret': 'void', 'fn': 'DrvGetPrinterData', 'args': ['str', 'str', 'ptr', 'ptr', 'long', 'ptr']},
    {'ord': '300', 'convention': 'pascal', 'ret': 'void', 'fn': 'EngineEnumerateFont', 'args': ['str', 'segptr', 'long']},
    {'ord': '301', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EngineDeleteFont', 'args': ['ptr']},
    {'ord': '302', 'convention': 'pascal', 'ret': 'void', 'fn': 'EngineRealizeFont', 'args': ['ptr', 'ptr', 'ptr']},
    {'ord': '303', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EngineGetCharWidth', 'args': ['ptr', 'word', 'word', 'ptr']},
    {'ord': '304', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EngineSetFontContext', 'args': ['ptr', 'word']},
    {'ord': '305', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EngineGetGlyphBMP', 'args': ['word', 'ptr', 'word', 'word', 'ptr', 'long', 'ptr']},
    {'ord': '306', 'convention': 'pascal', 'ret': 'void', 'fn': 'EngineMakeFontDir', 'args': ['word', 'ptr', 'ptr']},
    {'ord': '307', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetCharABCWidths', 'args': ['word', 'word', 'word', 'ptr']},
    {'ord': '308', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetOutlineTextMetrics', 'args': ['word', 'word', 'ptr']},
    {'ord': '309', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetGlyphOutline', 'args': ['word', 'word', 'word', 'ptr', 'long', 'ptr', 'ptr']},
    {'ord': '310', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateScalableFontResource', 'args': ['word', 'str', 'str', 'str']},
    {'ord': '311', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetFontData', 'args': ['word', 'long', 'long', 'ptr', 'long']},
    {'ord': '313', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetRasterizerCaps', 'args': ['ptr', 'word']},
    {'ord': '315', 'convention': 'pascal', 'ret': 'void', 'fn': 'EngineRealizeFontExt', 'args': ['long', 'long', 'long', 'long']},
    {'ord': '330', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EnumFontFamilies', 'args': ['word', 'str', 'segptr', 'long']},
    {'ord': '332', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetKerningPairs', 'args': ['word', 'word', 'ptr']},
    {'ord': '345', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetTextAlign', 'args': ['word']},
    {'ord': '346', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetTextAlign', 'args': ['word', 'word']},
    {'ord': '348', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'Chord', 'args': ['word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '349', 'convention': 'pascal', 'ret': 'void', 'fn': 'SetMapperFlags', 'args': ['word', 'long']},
    {'ord': '350', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetCharWidth', 'args': ['word', 'word', 'word', 'ptr']},
    {'ord': '351', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'ExtTextOut', 'args': ['word', 's_word', 's_word', 'word', 'ptr', 'str', 'word', 'ptr']},
    {'ord': '360', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreatePalette', 'args': ['ptr']},
    {'ord': '361', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GDISelectPalette', 'args': ['word', 'word', 'word']},
    {'ord': '362', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GDIRealizePalette', 'args': ['word']},
    {'ord': '363', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetPaletteEntries', 'args': ['word', 'word', 'word', 'ptr']},
    {'ord': '364', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetPaletteEntries', 'args': ['word', 'word', 'word', 'ptr']},
    {'ord': '365', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'RealizeDefaultPalette', 'args': ['word']},
    {'ord': '366', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'UpdateColors', 'args': ['word']},
    {'ord': '367', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'AnimatePalette', 'args': ['word', 'word', 'word', 'ptr']},
    {'ord': '368', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'ResizePalette', 'args': ['word', 'word']},
    {'ord': '370', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetNearestPaletteIndex', 'args': ['word', 'long']},
    {'ord': '372', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'ExtFloodFill', 'args': ['word', 's_word', 's_word', 'long', 'word']},
    {'ord': '373', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetSystemPaletteUse', 'args': ['word', 'word']},
    {'ord': '374', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetSystemPaletteUse', 'args': ['word']},
    {'ord': '375', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetSystemPaletteEntries', 'args': ['word', 'word', 'word', 'ptr']},
    {'ord': '376', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'ResetDC', 'args': ['word', 'ptr']},
    {'ord': '377', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'StartDoc', 'args': ['word', 'ptr']},
    {'ord': '378', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EndDoc', 'args': ['word']},
    {'ord': '379', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'StartPage', 'args': ['word']},
    {'ord': '380', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EndPage', 'args': ['word']},
    {'ord': '381', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetAbortProc', 'args': ['word', 'segptr']},
    {'ord': '382', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'AbortDoc', 'args': ['word']},
    {'ord': '400', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'FastWindowFrame', 'args': ['word', 'ptr', 's_word', 's_word', 'long']},
    {'ord': '403', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GdiInit2', 'args': ['word', 'word']},
    {'ord': '405', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'FinalGdiInit', 'args': ['word']},
    {'ord': '407', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateUserBitmap', 'args': ['word', 'word', 'word', 'word', 'ptr']},
    {'ord': '409', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateUserDiscardableBitmap', 'args': ['word', 'word', 'word']},
    {'ord': '410', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'IsValidMetaFile', 'args': ['word']},
    {'ord': '411', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetCurLogFont', 'args': ['word']},
    {'ord': '412', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'IsDCCurrentPalette', 'args': ['word']},
    {'ord': '439', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'StretchDIBits', 'args': ['word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word', 'ptr', 'ptr', 'word', 'long']},
    {'ord': '440', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetDIBits', 'args': ['word', 'word', 'word', 'word', 'ptr', 'ptr', 'word']},
    {'ord': '441', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetDIBits', 'args': ['word', 'word', 'word', 'word', 'ptr', 'ptr', 'word']},
    {'ord': '442', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateDIBitmap', 'args': ['word', 'ptr', 'long', 'ptr', 'ptr', 'word']},
    {'ord': '443', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetDIBitsToDevice', 'args': ['word', 's_word', 's_word', 's_word', 's_word', 's_word', 's_word', 'word', 'word', 'ptr', 'ptr', 'word']},
    {'ord': '444', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateRoundRectRgn', 'args': ['s_word', 's_word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '445', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateDIBPatternBrush', 'args': ['word', 'word']},
    {'ord': '450', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'PolyPolygon', 'args': ['word', 'ptr', 'ptr', 'word']},
    {'ord': '451', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreatePolyPolygonRgn', 'args': ['ptr', 'ptr', 'word', 'word']},
    {'ord': '452', 'convention': 'pascal', 'ret': 'void', 'fn': 'GdiSeeGdiDo', 'args': ['word', 'word', 'word', 'word']},
    {'ord': '461', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetObjectOwner', 'args': ['word', 'word']},
    {'ord': '462', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'IsGDIObject', 'args': ['word']},
    {'ord': '463', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'MakeObjectPrivate', 'args': ['word', 'word']},
    {'ord': '465', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'RectVisible', 'args': ['word', 'ptr']},
    {'ord': '466', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'RectInRegion', 'args': ['word', 'ptr']},
    {'ord': '468', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetBitmapDimensionEx', 'args': ['word', 'ptr']},
    {'ord': '469', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetBrushOrgEx', 'args': ['word', 'ptr']},
    {'ord': '470', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetCurrentPositionEx', 'args': ['word', 'ptr']},
    {'ord': '471', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetTextExtentPoint', 'args': ['word', 'ptr', 's_word', 'ptr']},
    {'ord': '472', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetViewportExtEx', 'args': ['word', 'ptr']},
    {'ord': '473', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetViewportOrgEx', 'args': ['word', 'ptr']},
    {'ord': '474', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetWindowExtEx', 'args': ['word', 'ptr']},
    {'ord': '475', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetWindowOrgEx', 'args': ['word', 'ptr']},
    {'ord': '476', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'OffsetViewportOrgEx', 'args': ['word', 's_word', 's_word', 'ptr']},
    {'ord': '477', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'OffsetWindowOrgEx', 'args': ['word', 's_word', 's_word', 'ptr']},
    {'ord': '478', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetBitmapDimensionEx', 'args': ['word', 's_word', 's_word', 'ptr']},
    {'ord': '479', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetViewportExtEx', 'args': ['word', 's_word', 's_word', 'ptr']},
    {'ord': '480', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetViewportOrgEx', 'args': ['word', 's_word', 's_word', 'ptr']},
    {'ord': '481', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetWindowExtEx', 'args': ['word', 's_word', 's_word', 'ptr']},
    {'ord': '482', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetWindowOrgEx', 'args': ['word', 's_word', 's_word', 'ptr']},
    {'ord': '483', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'MoveToEx', 'args': ['word', 's_word', 's_word', 'ptr']},
    {'ord': '484', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'ScaleViewportExtEx', 'args': ['word', 's_word', 's_word', 's_word', 's_word', 'ptr']},
    {'ord': '485', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'ScaleWindowExtEx', 'args': ['word', 's_word', 's_word', 's_word', 's_word', 'ptr']},
    {'ord': '486', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetAspectRatioFilterEx', 'args': ['word', 'ptr']},
    {'ord': '489', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateDIBSection', 'args': ['word', 'ptr', 'word', 'ptr', 'long', 'long']},
    {'ord': '502', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'PolyBezier', 'args': ['word', 'ptr', 'word']},
    {'ord': '503', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'PolyBezierTo', 'args': ['word', 'ptr', 'word']},
    {'ord': '508', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'ExtSelectClipRgn', 'args': ['word', 'word', 'word']},
    {'ord': '511', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'AbortPath', 'args': ['word']},
    {'ord': '512', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BeginPath', 'args': ['word']},
    {'ord': '513', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CloseFigure', 'args': ['word']},
    {'ord': '514', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EndPath', 'args': ['word']},
    {'ord': '515', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'FillPath', 'args': ['word']},
    {'ord': '516', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'FlattenPath', 'args': ['word']},
    {'ord': '517', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetPath', 'args': ['word', 'ptr', 'ptr', 'word']},
    {'ord': '518', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'PathToRegion', 'args': ['word']},
    {'ord': '519', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SelectClipPath', 'args': ['word', 'word']},
    {'ord': '520', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'StrokeAndFillPath', 'args': ['word']},
    {'ord': '521', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'StrokePath', 'args': ['word']},
    {'ord': '522', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'WidenPath', 'args': ['word']},
    {'ord': '524', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetArcDirection', 'args': ['word']},
    {'ord': '525', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetArcDirection', 'args': ['word', 'word']},
    {'ord': '529', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'CreateHalftonePalette', 'args': ['word']},
    {'ord': '530', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'RawTextOut', 'args': []},
    {'ord': '531', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'RawExtTextOut', 'args': []},
    {'ord': '532', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'RawGetTextExtent', 'args': ['word', 'str', 'word']},
    {'ord': '536', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiLayout', 'args': []},
    {'ord': '538', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiCreateTabString', 'args': []},
    {'ord': '540', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiGlyphOut', 'args': []},
    {'ord': '543', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiGetStringExtent', 'args': []},
    {'ord': '555', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiDeleteString', 'args': []},
    {'ord': '556', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiSetDefaults', 'args': []},
    {'ord': '558', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiGetDefaults', 'args': []},
    {'ord': '560', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiShape', 'args': []},
    {'ord': '561', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiFontComplement', 'args': []},
    {'ord': '564', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiSetKashida', 'args': []},
    {'ord': '565', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiKExtTextOut', 'args': []},
    {'ord': '566', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiShapeEx', 'args': []},
    {'ord': '569', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiCreateStringEx', 'args': []},
    {'ord': '571', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetTextExtentRtoL', 'args': []},
    {'ord': '572', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetHDCCharSet', 'args': []},
    {'ord': '573', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'BiDiLayoutEx', 'args': []},
    {'ord': '602', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetDIBColorTable', 'args': ['word', 'word', 'word', 'ptr']},
    {'ord': '603', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetDIBColorTable', 'args': ['word', 'word', 'word', 'ptr']},
    {'ord': '604', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetSolidBrush', 'args': ['word', 'long']},
    {'ord': '605', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SysDeleteObject', 'args': ['word']},
    {'ord': '606', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetMagicColors', 'args': ['word', 'long', 'word']},
    {'ord': '607', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetRegionData', 'args': ['word', 'long', 'ptr']},
    {'ord': '609', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GdiFreeResources', 'args': ['long']},
    {'ord': '610', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GdiSignalProc32', 'args': ['long', 'long', 'long', 'word']},
    {'ord': '612', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'GetTextCharset', 'args': ['word']},
    {'ord': '613', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'EnumFontFamiliesEx', 'args': ['word', 'ptr', 'segptr', 'long', 'long']},
    {'ord': '616', 'convention': 'pascal', 'ret': 'void', 'fn': 'GetFontLanguageInfo', 'args': ['word']},
    {'ord': '1000', 'convention': 'pascal', 'ret': '-ret16', 'fn': 'SetLayout', 'args': ['word', 'long']}
]