# Missing fns:
# GetVersion (returns as DX:AX)

kernel_fns = [
    {'ord': '2', 'convention': 'pascal', 'fn': 'ExitKernel', 'args': []},
    {'ord': '4', 'convention': 'pascal', 'fn': 'LocalInit', 'args': ['word', 'word', 'word']},
    {'ord': '5', 'convention': 'pascal', 'fn': 'LocalAlloc', 'args': ['word', 'word']},
    {'ord': '6', 'convention': 'pascal', 'fn': 'LocalReAlloc', 'args': ['word', 'word', 'word']},
    {'ord': '7', 'convention': 'pascal', 'fn': 'LocalFree', 'args': ['word']},
    {'ord': '9', 'convention': 'pascal', 'fn': 'LocalUnlock', 'args': ['word']},
    {'ord': '10', 'convention': 'pascal', 'fn': 'LocalSize', 'args': ['word']},
    {'ord': '11', 'convention': 'pascal', 'fn': 'LocalHandle', 'args': ['word']},
    {'ord': '12', 'convention': 'pascal', 'fn': 'LocalFlags', 'args': ['word']},
    {'ord': '13', 'convention': 'pascal', 'fn': 'LocalCompact', 'args': ['word']},
    {'ord': '15', 'convention': 'pascal', 'fn': 'GlobalAlloc', 'args': ['word', 'long']},
    {'ord': '16', 'convention': 'pascal', 'fn': 'GlobalReAlloc', 'args': ['word', 'long', 'word']},
    {'ord': '17', 'convention': 'pascal', 'fn': 'GlobalFree', 'args': ['word']},
    {'ord': '19', 'convention': 'pascal', 'fn': 'GlobalUnlock', 'args': ['word']},
    {'ord': '22', 'convention': 'pascal', 'fn': 'GlobalFlags', 'args': ['word']},
    {'ord': '23', 'convention': 'pascal', 'fn': 'LockSegment', 'args': ['word']},
    {'ord': '24', 'convention': 'pascal', 'fn': 'UnlockSegment', 'args': ['word']},
    {'ord': '26', 'convention': 'pascal', 'fn': 'GlobalFreeAll', 'args': ['word']},
    {'ord': '27', 'convention': 'pascal', 'fn': 'GetModuleName', 'args': ['word', 'ptr', 'word']},
    {'ord': '29', 'convention': 'pascal', 'fn': 'Yield', 'args': []},
    {'ord': '30', 'convention': 'pascal', 'fn': 'WaitEvent', 'args': ['word']},
    {'ord': '31', 'convention': 'pascal', 'fn': 'PostEvent', 'args': ['word']},
    {'ord': '32', 'convention': 'pascal', 'fn': 'SetPriority', 'args': ['word', 's_word']},
    {'ord': '33', 'convention': 'pascal', 'fn': 'LockCurrentTask', 'args': ['word']},
    {'ord': '34', 'convention': 'pascal', 'fn': 'SetTaskQueue', 'args': ['word', 'word']},
    {'ord': '35', 'convention': 'pascal', 'fn': 'GetTaskQueue', 'args': ['word']},
    {'ord': '41', 'convention': 'pascal', 'fn': 'EnableDos', 'args': []},
    {'ord': '42', 'convention': 'pascal', 'fn': 'DisableDos', 'args': []},
    {'ord': '45', 'convention': 'pascal', 'fn': 'LoadModule', 'args': ['str', 'ptr']},
    {'ord': '46', 'convention': 'pascal', 'fn': 'FreeModule', 'args': ['word']},
    {'ord': '48', 'convention': 'pascal', 'fn': 'GetModuleUsage', 'args': ['word']},
    {'ord': '49', 'convention': 'pascal', 'fn': 'GetModuleFileName', 'args': ['word', 'ptr', 's_word']},
    {'ord': '52', 'convention': 'pascal', 'fn': 'FreeProcInstance', 'args': ['segptr']},
    {'ord': '54', 'convention': 'pascal', 'fn': 'GetInstanceData', 'args': ['word', 'word', 'word']},
    {'ord': '55', 'convention': 'pascal', 'fn': 'Catch', 'args': ['ptr']},
    {'ord': '56', 'convention': 'pascal', 'fn': 'Throw', 'args': ['ptr', 'word']},
    {'ord': '57', 'convention': 'pascal', 'fn': 'GetProfileInt', 'args': ['str', 'str', 's_word']},
    {'ord': '58', 'convention': 'pascal', 'fn': 'GetProfileString', 'args': ['str', 'str', 'str', 'ptr', 'word']},
    {'ord': '59', 'convention': 'pascal', 'fn': 'WriteProfileString', 'args': ['str', 'str', 'str']},
    {'ord': '60', 'convention': 'pascal', 'fn': 'FindResource', 'args': ['word', 'str', 'str']},
    {'ord': '61', 'convention': 'pascal', 'fn': 'LoadResource', 'args': ['word', 'word']},
    {'ord': '63', 'convention': 'pascal', 'fn': 'FreeResource', 'args': ['word']},
    {'ord': '64', 'convention': 'pascal', 'fn': 'AccessResource', 'args': ['word', 'word']},
    {'ord': '66', 'convention': 'pascal', 'fn': 'AllocResource', 'args': ['word', 'word', 'long']},
    {'ord': '68', 'convention': 'pascal', 'fn': 'InitAtomTable', 'args': ['word']},
    {'ord': '69', 'convention': 'pascal', 'fn': 'FindAtom', 'args': ['str']},
    {'ord': '70', 'convention': 'pascal', 'fn': 'AddAtom', 'args': ['str']},
    {'ord': '71', 'convention': 'pascal', 'fn': 'DeleteAtom', 'args': ['word']},
    {'ord': '72', 'convention': 'pascal', 'fn': 'GetAtomName', 'args': ['word', 'ptr', 'word']},
    {'ord': '73', 'convention': 'pascal', 'fn': 'GetAtomHandle', 'args': ['word']},
    {'ord': '74', 'convention': 'pascal', 'fn': 'OpenFile', 'args': ['str', 'ptr', 'word']},
    {'ord': '81', 'convention': 'pascal', 'fn': '_lclose', 'args': ['word']},
    {'ord': '82', 'convention': 'pascal', 'fn': '_lread', 'args': ['word', 'segptr', 'word']},
    {'ord': '83', 'convention': 'pascal', 'fn': '_lcreat', 'args': ['str', 'word']},
    {'ord': '85', 'convention': 'pascal', 'fn': '_lopen', 'args': ['str', 'word']},
    {'ord': '86', 'convention': 'pascal', 'fn': '_lwrite', 'args': ['word', 'ptr', 'word']},
    {'ord': '87', 'convention': 'pascal', 'fn': 'Reserved5', 'args': ['str', 'str']},
    {'ord': '90', 'convention': 'pascal', 'fn': 'lstrlen', 'args': ['str']},
    {'ord': '91', 'convention': 'pascal', 'fn': 'InitTask', 'args': []},
    {'ord': '94', 'convention': 'pascal', 'fn': 'DefineHandleTable', 'args': ['word']},
    {'ord': '95', 'convention': 'pascal', 'fn': 'LoadLibrary', 'args': ['str']},
    {'ord': '96', 'convention': 'pascal', 'fn': 'FreeLibrary', 'args': ['word']},
    {'ord': '97', 'convention': 'pascal', 'fn': 'GetTempFileName', 'args': ['word', 'str', 'word', 'ptr']},
    {'ord': '98', 'convention': 'pascal', 'fn': 'GetLastDiskChange', 'args': []},
    {'ord': '100', 'convention': 'pascal', 'fn': 'ValidateCodeSegments', 'args': []},
    {'ord': '102', 'convention': 'pascal', 'fn': 'DOS3Call', 'args': []},
    {'ord': '103', 'convention': 'pascal', 'fn': 'NetBIOSCall', 'args': []},
    {'ord': '104', 'convention': 'pascal', 'fn': 'GetCodeInfo', 'args': ['segptr', 'ptr']},
    {'ord': '105', 'convention': 'pascal', 'fn': 'GetExeVersion', 'args': []},
    {'ord': '107', 'convention': 'pascal', 'fn': 'SetErrorMode', 'args': ['word']},
    {'ord': '108', 'convention': 'pascal', 'fn': 'SwitchStackTo', 'args': ['word', 'word', 'word']},
    {'ord': '109', 'convention': 'pascal', 'fn': 'SwitchStackBack', 'args': []},
    {'ord': '112', 'convention': 'pascal', 'fn': 'GlobalUnWire', 'args': ['word']},
    {'ord': '115', 'convention': 'pascal', 'fn': 'OutputDebugString', 'args': ['str']},
    {'ord': '117', 'convention': 'pascal', 'fn': 'OldYield', 'args': []},
    {'ord': '118', 'convention': 'pascal', 'fn': 'GetTaskQueueDS', 'args': []},
    {'ord': '119', 'convention': 'pascal', 'fn': 'GetTaskQueueES', 'args': []},
    {'ord': '121', 'convention': 'pascal', 'fn': 'LocalShrink', 'args': ['word', 'word']},
    {'ord': '122', 'convention': 'pascal', 'fn': 'IsTaskLocked', 'args': []},
    {'ord': '123', 'convention': 'pascal', 'fn': 'KbdRst', 'args': []},
    {'ord': '124', 'convention': 'pascal', 'fn': 'EnableKernel', 'args': []},
    {'ord': '125', 'convention': 'pascal', 'fn': 'DisableKernel', 'args': []},
    {'ord': '127', 'convention': 'pascal', 'fn': 'GetPrivateProfileInt', 'args': ['str', 'str', 's_word', 'str']},
    {'ord': '128', 'convention': 'pascal', 'fn': 'GetPrivateProfileString', 'args': ['str', 'str', 'str', 'ptr', 'word', 'str']},
    {'ord': '129', 'convention': 'pascal', 'fn': 'WritePrivateProfileString', 'args': ['str', 'str', 'str', 'str']},
    {'ord': '133', 'convention': 'pascal', 'fn': 'GetExePtr', 'args': ['word']},
    {'ord': '134', 'convention': 'pascal', 'fn': 'GetWindowsDirectory', 'args': ['ptr', 'word']},
    {'ord': '135', 'convention': 'pascal', 'fn': 'GetSystemDirectory', 'args': ['ptr', 'word']},
    {'ord': '136', 'convention': 'pascal', 'fn': 'GetDriveType', 'args': ['word']},
    {'ord': '137', 'convention': 'pascal', 'fn': 'FatalAppExit', 'args': ['word', 'str']},
    {'ord': '140', 'convention': 'pascal', 'fn': 'SetSigHandler', 'args': ['segptr', 'ptr', 'ptr', 'word', 'word']},
    {'ord': '142', 'convention': 'pascal', 'fn': 'GetProfileSectionNames', 'args': ['ptr', 'word']},
    {'ord': '143', 'convention': 'pascal', 'fn': 'GetPrivateProfileSectionNames', 'args': ['ptr', 'word', 'str']},
    {'ord': '144', 'convention': 'pascal', 'fn': 'CreateDirectory', 'args': ['ptr', 'ptr']},
    {'ord': '145', 'convention': 'pascal', 'fn': 'RemoveDirectory', 'args': ['ptr']},
    {'ord': '146', 'convention': 'pascal', 'fn': 'DeleteFile', 'args': ['ptr']},
    {'ord': '147', 'convention': 'pascal', 'fn': 'SetLastError', 'args': ['long']},
    {'ord': '149', 'convention': 'pascal', 'fn': 'GetVersionEx', 'args': ['ptr']},
    {'ord': '150', 'convention': 'pascal', 'fn': 'DirectedYield', 'args': ['word']},
    {'ord': '152', 'convention': 'pascal', 'fn': 'GetNumTasks', 'args': []},
    {'ord': '154', 'convention': 'pascal', 'fn': 'GlobalNotify', 'args': ['segptr']},
    {'ord': '155', 'convention': 'pascal', 'fn': 'GetTaskDS', 'args': []},
    {'ord': '158', 'convention': 'pascal', 'fn': 'IsWinOldApTask', 'args': ['word']},
    {'ord': '161', 'convention': 'pascal', 'fn': 'LocalCountFree', 'args': []},
    {'ord': '162', 'convention': 'pascal', 'fn': 'LocalHeapSize', 'args': []},
    {'ord': '163', 'convention': 'pascal', 'fn': 'GlobalLRUOldest', 'args': ['word']},
    {'ord': '164', 'convention': 'pascal', 'fn': 'GlobalLRUNewest', 'args': ['word']},
    {'ord': '165', 'convention': 'pascal', 'fn': 'A20Proc', 'args': ['word']},
    {'ord': '166', 'convention': 'pascal', 'fn': 'WinExec', 'args': ['str', 'word']},
    {'ord': '167', 'convention': 'pascal', 'fn': 'GetExpWinVer', 'args': ['word']},
    {'ord': '168', 'convention': 'pascal', 'fn': 'DirectResAlloc', 'args': ['word', 'word', 'word']},
    {'ord': '170', 'convention': 'pascal', 'fn': 'AllocCStoDSAlias', 'args': ['word']},
    {'ord': '171', 'convention': 'pascal', 'fn': 'AllocDStoCSAlias', 'args': ['word']},
    {'ord': '172', 'convention': 'pascal', 'fn': 'AllocAlias', 'args': ['word']},
    {'ord': '175', 'convention': 'pascal', 'fn': 'AllocSelector', 'args': ['word']},
    {'ord': '176', 'convention': 'pascal', 'fn': 'FreeSelector', 'args': ['word']},
    {'ord': '177', 'convention': 'pascal', 'fn': 'PrestoChangoSelector', 'args': ['word', 'word']},
    {'ord': '180', 'convention': 'pascal', 'fn': 'LongPtrAdd', 'args': ['long', 'long']},
    {'ord': '185', 'convention': 'pascal', 'fn': 'GlobalDOSFree', 'args': ['word']},
    {'ord': '187', 'convention': 'pascal', 'fn': 'SetSelectorBase', 'args': ['word', 'long']},
    {'ord': '189', 'convention': 'pascal', 'fn': 'SetSelectorLimit', 'args': ['word', 'long']},
    {'ord': '191', 'convention': 'pascal', 'fn': 'GlobalPageLock', 'args': ['word']},
    {'ord': '192', 'convention': 'pascal', 'fn': 'GlobalPageUnlock', 'args': ['word']},
    {'ord': '196', 'convention': 'pascal', 'fn': 'SelectorAccessRights', 'args': ['word', 'word', 'word']},
    {'ord': '197', 'convention': 'pascal', 'fn': 'GlobalFix', 'args': ['word']},
    {'ord': '198', 'convention': 'pascal', 'fn': 'GlobalUnfix', 'args': ['word']},
    {'ord': '199', 'convention': 'pascal', 'fn': 'SetHandleCount', 'args': ['word']},
    {'ord': '200', 'convention': 'pascal', 'fn': 'ValidateFreeSpaces', 'args': []},
    {'ord': '203', 'convention': 'pascal', 'fn': 'DebugBreak', 'args': []},
    {'ord': '206', 'convention': 'pascal', 'fn': 'AllocSelectorArray', 'args': ['word']},
    {'ord': '207', 'convention': 'pascal', 'fn': 'IsDBCSLeadByte', 'args': ['word']},
    {'ord': '310', 'convention': 'pascal', 'fn': 'LocalHandleDelta', 'args': ['word']},
    {'ord': '315', 'convention': 'pascal', 'fn': 'WriteOutProfiles', 'args': []},
    {'ord': '320', 'convention': 'pascal', 'fn': 'IsTask', 'args': ['word']},
    {'ord': '323', 'convention': 'pascal', 'fn': 'IsRomModule', 'args': ['word']},
    {'ord': '324', 'convention': 'pascal', 'fn': 'LogError', 'args': ['word', 'ptr']},
    {'ord': '325', 'convention': 'pascal', 'fn': 'LogParamError', 'args': ['word', 'ptr', 'ptr']},
    {'ord': '326', 'convention': 'pascal', 'fn': 'IsRomFile', 'args': ['word']},
    {'ord': '327', 'convention': 'pascal', 'fn': 'K327', 'args': []},
    {'ord': '328', 'convention': 'varargs', 'fn': '_DebugOutput', 'args': ['word', 'str']},
    {'ord': '329', 'convention': 'pascal', 'fn': 'K329', 'args': ['str', 'word']},
    {'ord': '334', 'convention': 'pascal', 'fn': 'IsBadReadPtr', 'args': ['segptr', 'word']},
    {'ord': '335', 'convention': 'pascal', 'fn': 'IsBadWritePtr', 'args': ['segptr', 'word']},
    {'ord': '336', 'convention': 'pascal', 'fn': 'IsBadCodePtr', 'args': ['segptr']},
    {'ord': '337', 'convention': 'pascal', 'fn': 'IsBadStringPtr', 'args': ['segptr', 'word']},
    {'ord': '338', 'convention': 'pascal', 'fn': 'HasGPHandler', 'args': ['segptr']},
    {'ord': '339', 'convention': 'pascal', 'fn': 'DiagQuery', 'args': []},
    {'ord': '340', 'convention': 'pascal', 'fn': 'DiagOutput', 'args': ['str']},
    {'ord': '345', 'convention': 'pascal', 'fn': 'IsSharedSelector', 'args': ['word']},
    {'ord': '346', 'convention': 'pascal', 'fn': 'IsBadHugeReadPtr', 'args': ['segptr', 'long']},
    {'ord': '347', 'convention': 'pascal', 'fn': 'IsBadHugeWritePtr', 'args': ['segptr', 'long']},
    {'ord': '348', 'convention': 'pascal', 'fn': 'hmemcpy', 'args': ['ptr', 'ptr', 'long']},
    {'ord': '351', 'convention': 'pascal', 'fn': 'BUNNY_351', 'args': []},
    {'ord': '355', 'convention': 'pascal', 'fn': 'GetWinDebugInfo', 'args': ['ptr', 'word']},
    {'ord': '356', 'convention': 'pascal', 'fn': 'SetWinDebugInfo', 'args': ['ptr']},
    {'ord': '403', 'convention': 'pascal', 'fn': 'FarSetOwner', 'args': ['word', 'word']},
    {'ord': '404', 'convention': 'pascal', 'fn': 'FarGetOwner', 'args': ['word']},
]
