# Missing fns:
# USER.DispatchMessage (ord 114)
# USER.GetCurrentTime (ord 13)

user_fns = [
    {'ord': '1', 'convention': 'pascal', 'fn': 'MessageBox', 'args': ['word', 'str', 'str', 'word']},
    {'ord': '2', 'convention': 'pascal', 'fn': 'OldExitWindows', 'args': []},
    {'ord': '5', 'convention': 'pascal', 'fn': 'InitApp', 'args': ['word']},
    {'ord': '6', 'convention': 'pascal', 'fn': 'PostQuitMessage', 'args': ['word']},
    {'ord': '7', 'convention': 'pascal', 'fn': 'ExitWindows', 'args': ['long', 'word']},
    {'ord': '10', 'convention': 'pascal', 'fn': 'SetTimer', 'args': ['word', 'word', 'word', 'segptr']},
    {'ord': '11', 'convention': 'pascal', 'fn': 'SetSystemTimer', 'args': ['word', 'word', 'word', 'segptr']},
    {'ord': '12', 'convention': 'pascal', 'fn': 'KillTimer', 'args': ['word', 'word']},
    {'ord': '16', 'convention': 'pascal', 'fn': 'ClipCursor', 'args': ['ptr']},
    {'ord': '17', 'convention': 'pascal', 'fn': 'GetCursorPos', 'args': ['ptr']},
    {'ord': '18', 'convention': 'pascal', 'fn': 'SetCapture', 'args': ['word']},
    {'ord': '19', 'convention': 'pascal', 'fn': 'ReleaseCapture', 'args': []},
    {'ord': '20', 'convention': 'pascal', 'fn': 'SetDoubleClickTime', 'args': ['word']},
    {'ord': '21', 'convention': 'pascal', 'fn': 'GetDoubleClickTime', 'args': []},
    {'ord': '22', 'convention': 'pascal', 'fn': 'SetFocus', 'args': ['word']},
    {'ord': '23', 'convention': 'pascal', 'fn': 'GetFocus', 'args': []},
    {'ord': '24', 'convention': 'pascal', 'fn': 'RemoveProp', 'args': ['word', 'ptr']},
    {'ord': '25', 'convention': 'pascal', 'fn': 'GetProp', 'args': ['word', 'str']},
    {'ord': '26', 'convention': 'pascal', 'fn': 'SetProp', 'args': ['word', 'str', 'word']},
    {'ord': '27', 'convention': 'pascal', 'fn': 'EnumProps', 'args': ['word', 'segptr']},
    {'ord': '28', 'convention': 'pascal', 'fn': 'ClientToScreen', 'args': ['word', 'ptr']},
    {'ord': '29', 'convention': 'pascal', 'fn': 'ScreenToClient', 'args': ['word', 'ptr']},
    {'ord': '30', 'convention': 'pascal', 'fn': 'WindowFromPoint', 'args': ['long']},
    {'ord': '31', 'convention': 'pascal', 'fn': 'IsIconic', 'args': ['word']},
    {'ord': '32', 'convention': 'pascal', 'fn': 'GetWindowRect', 'args': ['word', 'ptr']},
    {'ord': '33', 'convention': 'pascal', 'fn': 'GetClientRect', 'args': ['word', 'ptr']},
    {'ord': '34', 'convention': 'pascal', 'fn': 'EnableWindow', 'args': ['word', 'word']},
    {'ord': '35', 'convention': 'pascal', 'fn': 'IsWindowEnabled', 'args': ['word']},
    {'ord': '36', 'convention': 'pascal', 'fn': 'GetWindowText', 'args': ['word', 'segptr', 'word']},
    {'ord': '37', 'convention': 'pascal', 'fn': 'SetWindowText', 'args': ['word', 'segstr']},
    {'ord': '38', 'convention': 'pascal', 'fn': 'GetWindowTextLength', 'args': ['word']},
    {'ord': '39', 'convention': 'pascal', 'fn': 'BeginPaint', 'args': ['word', 'ptr']},
    {'ord': '40', 'convention': 'pascal', 'fn': 'EndPaint', 'args': ['word', 'ptr']},
    {'ord': '41', 'convention': 'pascal', 'fn': 'CreateWindow', 'args': ['str', 'str', 'long', 's_word', 's_word', 's_word', 's_word', 'word', 'word', 'word', 'segptr']},
    {'ord': '42', 'convention': 'pascal', 'fn': 'ShowWindow', 'args': ['word', 'word']},
    {'ord': '43', 'convention': 'pascal', 'fn': 'CloseWindow', 'args': ['word']},
    {'ord': '44', 'convention': 'pascal', 'fn': 'OpenIcon', 'args': ['word']},
    {'ord': '45', 'convention': 'pascal', 'fn': 'BringWindowToTop', 'args': ['word']},
    {'ord': '46', 'convention': 'pascal', 'fn': 'GetParent', 'args': ['word']},
    {'ord': '47', 'convention': 'pascal', 'fn': 'IsWindow', 'args': ['word']},
    {'ord': '48', 'convention': 'pascal', 'fn': 'IsChild', 'args': ['word', 'word']},
    {'ord': '49', 'convention': 'pascal', 'fn': 'IsWindowVisible', 'args': ['word']},
    {'ord': '50', 'convention': 'pascal', 'fn': 'FindWindow', 'args': ['str', 'str']},
    {'ord': '52', 'convention': 'pascal', 'fn': 'AnyPopup', 'args': []},
    {'ord': '53', 'convention': 'pascal', 'fn': 'DestroyWindow', 'args': ['word']},
    {'ord': '54', 'convention': 'pascal', 'fn': 'EnumWindows', 'args': ['segptr', 'long']},
    {'ord': '55', 'convention': 'pascal', 'fn': 'EnumChildWindows', 'args': ['word', 'segptr', 'long']},
    {'ord': '56', 'convention': 'pascal', 'fn': 'MoveWindow', 'args': ['word', 'word', 'word', 'word', 'word', 'word']},
    {'ord': '57', 'convention': 'pascal', 'fn': 'RegisterClass', 'args': ['ptr']},
    {'ord': '58', 'convention': 'pascal', 'fn': 'GetClassName', 'args': ['word', 'ptr', 'word']},
    {'ord': '59', 'convention': 'pascal', 'fn': 'SetActiveWindow', 'args': ['word']},
    {'ord': '60', 'convention': 'pascal', 'fn': 'GetActiveWindow', 'args': []},
    {'ord': '61', 'convention': 'pascal', 'fn': 'ScrollWindow', 'args': ['word', 's_word', 's_word', 'ptr', 'ptr']},
    {'ord': '62', 'convention': 'pascal', 'fn': 'SetScrollPos', 'args': ['word', 'word', 's_word', 'word']},
    {'ord': '63', 'convention': 'pascal', 'fn': 'GetScrollPos', 'args': ['word', 'word']},
    {'ord': '64', 'convention': 'pascal', 'fn': 'SetScrollRange', 'args': ['word', 'word', 's_word', 's_word', 'word']},
    {'ord': '65', 'convention': 'pascal', 'fn': 'GetScrollRange', 'args': ['word', 'word', 'ptr', 'ptr']},
    {'ord': '66', 'convention': 'pascal', 'fn': 'GetDC', 'args': ['word']},
    {'ord': '67', 'convention': 'pascal', 'fn': 'GetWindowDC', 'args': ['word']},
    {'ord': '68', 'convention': 'pascal', 'fn': 'ReleaseDC', 'args': ['word', 'word']},
    {'ord': '69', 'convention': 'pascal', 'fn': 'SetCursor', 'args': ['word']},
    {'ord': '70', 'convention': 'pascal', 'fn': 'SetCursorPos', 'args': ['word', 'word']},
    {'ord': '71', 'convention': 'pascal', 'fn': 'ShowCursor', 'args': ['word']},
    {'ord': '72', 'convention': 'pascal', 'fn': 'SetRect', 'args': ['ptr', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '73', 'convention': 'pascal', 'fn': 'SetRectEmpty', 'args': ['ptr']},
    {'ord': '74', 'convention': 'pascal', 'fn': 'CopyRect', 'args': ['ptr', 'ptr']},
    {'ord': '75', 'convention': 'pascal', 'fn': 'IsRectEmpty', 'args': ['ptr']},
    {'ord': '76', 'convention': 'pascal', 'fn': 'PtInRect', 'args': ['ptr', 'long']},
    {'ord': '77', 'convention': 'pascal', 'fn': 'OffsetRect', 'args': ['ptr', 's_word', 's_word']},
    {'ord': '78', 'convention': 'pascal', 'fn': 'InflateRect', 'args': ['ptr', 's_word', 's_word']},
    {'ord': '79', 'convention': 'pascal', 'fn': 'IntersectRect', 'args': ['ptr', 'ptr', 'ptr']},
    {'ord': '80', 'convention': 'pascal', 'fn': 'UnionRect', 'args': ['ptr', 'ptr', 'ptr']},
    {'ord': '81', 'convention': 'pascal', 'fn': 'FillRect', 'args': ['word', 'ptr', 'word']},
    {'ord': '82', 'convention': 'pascal', 'fn': 'InvertRect', 'args': ['word', 'ptr']},
    {'ord': '83', 'convention': 'pascal', 'fn': 'FrameRect', 'args': ['word', 'ptr', 'word']},
    {'ord': '84', 'convention': 'pascal', 'fn': 'DrawIcon', 'args': ['word', 's_word', 's_word', 'word']},
    {'ord': '85', 'convention': 'pascal', 'fn': 'DrawText', 'args': ['word', 'str', 's_word', 'ptr', 'word']},
    {'ord': '87', 'convention': 'pascal', 'fn': 'DialogBox', 'args': ['word', 'str', 'word', 'segptr']},
    {'ord': '88', 'convention': 'pascal', 'fn': 'EndDialog', 'args': ['word', 's_word']},
    {'ord': '89', 'convention': 'pascal', 'fn': 'CreateDialog', 'args': ['word', 'str', 'word', 'segptr']},
    {'ord': '90', 'convention': 'pascal', 'fn': 'IsDialogMessage', 'args': ['word', 'ptr']},
    {'ord': '91', 'convention': 'pascal', 'fn': 'GetDlgItem', 'args': ['word', 'word']},
    {'ord': '92', 'convention': 'pascal', 'fn': 'SetDlgItemText', 'args': ['word', 'word', 'segstr']},
    {'ord': '93', 'convention': 'pascal', 'fn': 'GetDlgItemText', 'args': ['word', 'word', 'segptr', 'word']},
    {'ord': '94', 'convention': 'pascal', 'fn': 'SetDlgItemInt', 'args': ['word', 'word', 'word', 'word']},
    {'ord': '95', 'convention': 'pascal', 'fn': 'GetDlgItemInt', 'args': ['word', 's_word', 'ptr', 'word']},
    {'ord': '96', 'convention': 'pascal', 'fn': 'CheckRadioButton', 'args': ['word', 'word', 'word', 'word']},
    {'ord': '97', 'convention': 'pascal', 'fn': 'CheckDlgButton', 'args': ['word', 'word', 'word']},
    {'ord': '98', 'convention': 'pascal', 'fn': 'IsDlgButtonChecked', 'args': ['word', 'word']},
    {'ord': '99', 'convention': 'pascal', 'fn': 'DlgDirSelect', 'args': ['word', 'ptr', 'word']},
    {'ord': '100', 'convention': 'pascal', 'fn': 'DlgDirList', 'args': ['word', 'str', 'word', 'word', 'word']},
    {'ord': '102', 'convention': 'pascal', 'fn': 'AdjustWindowRect', 'args': ['ptr', 'long', 'word']},
    {'ord': '103', 'convention': 'pascal', 'fn': 'MapDialogRect', 'args': ['word', 'ptr']},
    {'ord': '104', 'convention': 'pascal', 'fn': 'MessageBeep', 'args': ['word']},
    {'ord': '105', 'convention': 'pascal', 'fn': 'FlashWindow', 'args': ['word', 'word']},
    {'ord': '106', 'convention': 'pascal', 'fn': 'GetKeyState', 'args': ['word']},
    {'ord': '108', 'convention': 'pascal', 'fn': 'GetMessage', 'args': ['ptr', 'word', 'word', 'word']},
    {'ord': '109', 'convention': 'pascal', 'fn': 'PeekMessage', 'args': ['ptr', 'word', 'word', 'word', 'word']},
    {'ord': '110', 'convention': 'pascal', 'fn': 'PostMessage', 'args': ['word', 'word', 'word', 'long']},
    {'ord': '112', 'convention': 'pascal', 'fn': 'WaitMessage', 'args': []},
    {'ord': '113', 'convention': 'pascal', 'fn': 'TranslateMessage', 'args': ['ptr']},
    {'ord': '115', 'convention': 'pascal', 'fn': 'ReplyMessage', 'args': ['long']},
    {'ord': '116', 'convention': 'pascal', 'fn': 'PostAppMessage', 'args': ['word', 'word', 'word', 'long']},
    {'ord': '117', 'convention': 'pascal', 'fn': 'WindowFromDC', 'args': ['word']},
    {'ord': '118', 'convention': 'pascal', 'fn': 'RegisterWindowMessage', 'args': ['str']},
    {'ord': '123', 'convention': 'pascal', 'fn': 'CallMsgFilter', 'args': ['ptr', 's_word']},
    {'ord': '124', 'convention': 'pascal', 'fn': 'UpdateWindow', 'args': ['word']},
    {'ord': '125', 'convention': 'pascal', 'fn': 'InvalidateRect', 'args': ['word', 'ptr', 'word']},
    {'ord': '126', 'convention': 'pascal', 'fn': 'InvalidateRgn', 'args': ['word', 'word', 'word']},
    {'ord': '127', 'convention': 'pascal', 'fn': 'ValidateRect', 'args': ['word', 'ptr']},
    {'ord': '128', 'convention': 'pascal', 'fn': 'ValidateRgn', 'args': ['word', 'word']},
    {'ord': '129', 'convention': 'pascal', 'fn': 'GetClassWord', 'args': ['word', 's_word']},
    {'ord': '130', 'convention': 'pascal', 'fn': 'SetClassWord', 'args': ['word', 's_word', 'word']},
    {'ord': '133', 'convention': 'pascal', 'fn': 'GetWindowWord', 'args': ['word', 's_word']},
    {'ord': '134', 'convention': 'pascal', 'fn': 'SetWindowWord', 'args': ['word', 's_word', 'word']},
    {'ord': '137', 'convention': 'pascal', 'fn': 'OpenClipboard', 'args': ['word']},
    {'ord': '138', 'convention': 'pascal', 'fn': 'CloseClipboard', 'args': []},
    {'ord': '139', 'convention': 'pascal', 'fn': 'EmptyClipboard', 'args': []},
    {'ord': '140', 'convention': 'pascal', 'fn': 'GetClipboardOwner', 'args': []},
    {'ord': '141', 'convention': 'pascal', 'fn': 'SetClipboardData', 'args': ['word', 'word']},
    {'ord': '142', 'convention': 'pascal', 'fn': 'GetClipboardData', 'args': ['word']},
    {'ord': '143', 'convention': 'pascal', 'fn': 'CountClipboardFormats', 'args': []},
    {'ord': '144', 'convention': 'pascal', 'fn': 'EnumClipboardFormats', 'args': ['word']},
    {'ord': '145', 'convention': 'pascal', 'fn': 'RegisterClipboardFormat', 'args': ['ptr']},
    {'ord': '146', 'convention': 'pascal', 'fn': 'GetClipboardFormatName', 'args': ['word', 'ptr', 's_word']},
    {'ord': '147', 'convention': 'pascal', 'fn': 'SetClipboardViewer', 'args': ['word']},
    {'ord': '148', 'convention': 'pascal', 'fn': 'GetClipboardViewer', 'args': []},
    {'ord': '149', 'convention': 'pascal', 'fn': 'ChangeClipboardChain', 'args': ['word', 'word']},
    {'ord': '150', 'convention': 'pascal', 'fn': 'LoadMenu', 'args': ['word', 'str']},
    {'ord': '151', 'convention': 'pascal', 'fn': 'CreateMenu', 'args': []},
    {'ord': '152', 'convention': 'pascal', 'fn': 'DestroyMenu', 'args': ['word']},
    {'ord': '153', 'convention': 'pascal', 'fn': 'ChangeMenu', 'args': ['word', 'word', 'segstr', 'word', 'word']},
    {'ord': '154', 'convention': 'pascal', 'fn': 'CheckMenuItem', 'args': ['word', 'word', 'word']},
    {'ord': '155', 'convention': 'pascal', 'fn': 'EnableMenuItem', 'args': ['word', 'word', 'word']},
    {'ord': '156', 'convention': 'pascal', 'fn': 'GetSystemMenu', 'args': ['word', 'word']},
    {'ord': '157', 'convention': 'pascal', 'fn': 'GetMenu', 'args': ['word']},
    {'ord': '158', 'convention': 'pascal', 'fn': 'SetMenu', 'args': ['word', 'word']},
    {'ord': '159', 'convention': 'pascal', 'fn': 'GetSubMenu', 'args': ['word', 'word']},
    {'ord': '160', 'convention': 'pascal', 'fn': 'DrawMenuBar', 'args': ['word']},
    {'ord': '161', 'convention': 'pascal', 'fn': 'GetMenuString', 'args': ['word', 'word', 'ptr', 's_word', 'word']},
    {'ord': '162', 'convention': 'pascal', 'fn': 'HiliteMenuItem', 'args': ['word', 'word', 'word', 'word']},
    {'ord': '163', 'convention': 'pascal', 'fn': 'CreateCaret', 'args': ['word', 'word', 'word', 'word']},
    {'ord': '164', 'convention': 'pascal', 'fn': 'DestroyCaret', 'args': []},
    {'ord': '165', 'convention': 'pascal', 'fn': 'SetCaretPos', 'args': ['word', 'word']},
    {'ord': '166', 'convention': 'pascal', 'fn': 'HideCaret', 'args': ['word']},
    {'ord': '167', 'convention': 'pascal', 'fn': 'ShowCaret', 'args': ['word']},
    {'ord': '168', 'convention': 'pascal', 'fn': 'SetCaretBlinkTime', 'args': ['word']},
    {'ord': '169', 'convention': 'pascal', 'fn': 'GetCaretBlinkTime', 'args': []},
    {'ord': '170', 'convention': 'pascal', 'fn': 'ArrangeIconicWindows', 'args': ['word']},
    {'ord': '171', 'convention': 'pascal', 'fn': 'WinHelp', 'args': ['word', 'str', 'word', 'long']},
    {'ord': '172', 'convention': 'pascal', 'fn': 'SwitchToThisWindow', 'args': ['word', 'word']},
    {'ord': '173', 'convention': 'pascal', 'fn': 'LoadCursor', 'args': ['word', 'str']},
    {'ord': '174', 'convention': 'pascal', 'fn': 'LoadIcon', 'args': ['word', 'str']},
    {'ord': '175', 'convention': 'pascal', 'fn': 'LoadBitmap', 'args': ['word', 'str']},
    {'ord': '176', 'convention': 'pascal', 'fn': 'LoadString', 'args': ['word', 'word', 'ptr', 's_word']},
    {'ord': '177', 'convention': 'pascal', 'fn': 'LoadAccelerators', 'args': ['word', 'str']},
    {'ord': '178', 'convention': 'pascal', 'fn': 'TranslateAccelerator', 'args': ['word', 'word', 'ptr']},
    {'ord': '179', 'convention': 'pascal', 'fn': 'GetSystemMetrics', 'args': ['s_word']},
    {'ord': '181', 'convention': 'pascal', 'fn': 'SetSysColors', 'args': ['word', 'ptr', 'ptr']},
    {'ord': '182', 'convention': 'pascal', 'fn': 'KillSystemTimer', 'args': ['word', 'word']},
    {'ord': '183', 'convention': 'pascal', 'fn': 'GetCaretPos', 'args': ['ptr']},
    {'ord': '185', 'convention': 'pascal', 'fn': 'GrayString', 'args': ['word', 'word', 'segptr', 'segptr', 's_word', 's_word', 's_word', 's_word', 's_word']},
    {'ord': '186', 'convention': 'pascal', 'fn': 'SwapMouseButton', 'args': ['word']},
    {'ord': '187', 'convention': 'pascal', 'fn': 'EndMenu', 'args': []},
    {'ord': '188', 'convention': 'pascal', 'fn': 'SetSysModalWindow', 'args': ['word']},
    {'ord': '189', 'convention': 'pascal', 'fn': 'GetSysModalWindow', 'args': []},
    {'ord': '190', 'convention': 'pascal', 'fn': 'GetUpdateRect', 'args': ['word', 'ptr', 'word']},
    {'ord': '191', 'convention': 'pascal', 'fn': 'ChildWindowFromPoint', 'args': ['word', 'long']},
    {'ord': '192', 'convention': 'pascal', 'fn': 'InSendMessage', 'args': []},
    {'ord': '193', 'convention': 'pascal', 'fn': 'IsClipboardFormatAvailable', 'args': ['word']},
    {'ord': '194', 'convention': 'pascal', 'fn': 'DlgDirSelectComboBox', 'args': ['word', 'ptr', 'word']},
    {'ord': '195', 'convention': 'pascal', 'fn': 'DlgDirListComboBox', 'args': ['word', 'ptr', 'word', 'word', 'word']},
    {'ord': '198', 'convention': 'pascal', 'fn': 'CascadeChildWindows', 'args': ['word', 'word']},
    {'ord': '199', 'convention': 'pascal', 'fn': 'TileChildWindows', 'args': ['word', 'word']},
    {'ord': '200', 'convention': 'pascal', 'fn': 'OpenComm', 'args': ['str', 'word', 'word']},
    {'ord': '201', 'convention': 'pascal', 'fn': 'SetCommState', 'args': ['ptr']},
    {'ord': '202', 'convention': 'pascal', 'fn': 'GetCommState', 'args': ['word', 'ptr']},
    {'ord': '203', 'convention': 'pascal', 'fn': 'GetCommError', 'args': ['word', 'ptr']},
    {'ord': '204', 'convention': 'pascal', 'fn': 'ReadComm', 'args': ['word', 'ptr', 'word']},
    {'ord': '205', 'convention': 'pascal', 'fn': 'WriteComm', 'args': ['word', 'ptr', 'word']},
    {'ord': '206', 'convention': 'pascal', 'fn': 'TransmitCommChar', 'args': ['word', 'word']},
    {'ord': '207', 'convention': 'pascal', 'fn': 'CloseComm', 'args': ['word']},
    {'ord': '209', 'convention': 'pascal', 'fn': 'GetCommEventMask', 'args': ['word', 'word']},
    {'ord': '210', 'convention': 'pascal', 'fn': 'SetCommBreak', 'args': ['word']},
    {'ord': '211', 'convention': 'pascal', 'fn': 'ClearCommBreak', 'args': ['word']},
    {'ord': '212', 'convention': 'pascal', 'fn': 'UngetCommChar', 'args': ['word', 'word']},
    {'ord': '213', 'convention': 'pascal', 'fn': 'BuildCommDCB', 'args': ['ptr', 'ptr']},
    {'ord': '215', 'convention': 'pascal', 'fn': 'FlushComm', 'args': ['word', 'word']},
    {'ord': '217', 'convention': 'pascal', 'fn': 'LookupMenuHandle', 'args': ['word', 's_word']},
    {'ord': '218', 'convention': 'pascal', 'fn': 'DialogBoxIndirect', 'args': ['word', 'word', 'word', 'segptr']},
    {'ord': '219', 'convention': 'pascal', 'fn': 'CreateDialogIndirect', 'args': ['word', 'ptr', 'word', 'segptr']},
    {'ord': '220', 'convention': 'pascal', 'fn': 'LoadMenuIndirect', 'args': ['ptr']},
    {'ord': '221', 'convention': 'pascal', 'fn': 'ScrollDC', 'args': ['word', 's_word', 's_word', 'ptr', 'ptr', 'word', 'ptr']},
    {'ord': '222', 'convention': 'pascal', 'fn': 'GetKeyboardState', 'args': ['ptr']},
    {'ord': '223', 'convention': 'pascal', 'fn': 'SetKeyboardState', 'args': ['ptr']},
    {'ord': '224', 'convention': 'pascal', 'fn': 'GetWindowTask', 'args': ['word']},
    {'ord': '225', 'convention': 'pascal', 'fn': 'EnumTaskWindows', 'args': ['word', 'segptr', 'long']},
    {'ord': '227', 'convention': 'pascal', 'fn': 'GetNextDlgGroupItem', 'args': ['word', 'word', 'word']},
    {'ord': '228', 'convention': 'pascal', 'fn': 'GetNextDlgTabItem', 'args': ['word', 'word', 'word']},
    {'ord': '229', 'convention': 'pascal', 'fn': 'GetTopWindow', 'args': ['word']},
    {'ord': '230', 'convention': 'pascal', 'fn': 'GetNextWindow', 'args': ['word', 'word']},
    {'ord': '231', 'convention': 'pascal', 'fn': 'GetSystemDebugState', 'args': []},
    {'ord': '232', 'convention': 'pascal', 'fn': 'SetWindowPos', 'args': ['word', 'word', 'word', 'word', 'word', 'word', 'word']},
    {'ord': '233', 'convention': 'pascal', 'fn': 'SetParent', 'args': ['word', 'word']},
    {'ord': '234', 'convention': 'pascal', 'fn': 'UnhookWindowsHook', 'args': ['s_word', 'segptr']},
    {'ord': '236', 'convention': 'pascal', 'fn': 'GetCapture', 'args': []},
    {'ord': '237', 'convention': 'pascal', 'fn': 'GetUpdateRgn', 'args': ['word', 'word', 'word']},
    {'ord': '238', 'convention': 'pascal', 'fn': 'ExcludeUpdateRgn', 'args': ['word', 'word']},
    {'ord': '239', 'convention': 'pascal', 'fn': 'DialogBoxParam', 'args': ['word', 'str', 'word', 'segptr', 'long']},
    {'ord': '240', 'convention': 'pascal', 'fn': 'DialogBoxIndirectParam', 'args': ['word', 'word', 'word', 'segptr', 'long']},
    {'ord': '241', 'convention': 'pascal', 'fn': 'CreateDialogParam', 'args': ['word', 'str', 'word', 'segptr', 'long']},
    {'ord': '242', 'convention': 'pascal', 'fn': 'CreateDialogIndirectParam', 'args': ['word', 'ptr', 'word', 'segptr', 'long']},
    {'ord': '244', 'convention': 'pascal', 'fn': 'EqualRect', 'args': ['ptr', 'ptr']},
    {'ord': '245', 'convention': 'pascal', 'fn': 'EnableCommNotification', 'args': ['s_word', 'word', 's_word', 's_word']},
    {'ord': '246', 'convention': 'pascal', 'fn': 'ExitWindowsExec', 'args': ['str', 'str']},
    {'ord': '247', 'convention': 'pascal', 'fn': 'GetCursor', 'args': []},
    {'ord': '248', 'convention': 'pascal', 'fn': 'GetOpenClipboardWindow', 'args': []},
    {'ord': '249', 'convention': 'pascal', 'fn': 'GetAsyncKeyState', 'args': ['word']},
    {'ord': '250', 'convention': 'pascal', 'fn': 'GetMenuState', 'args': ['word', 'word', 'word']},
    {'ord': '252', 'convention': 'pascal', 'fn': 'OpenDriver', 'args': ['str', 'str', 'long']},
    {'ord': '254', 'convention': 'pascal', 'fn': 'GetDriverModuleHandle', 'args': ['word']},
    {'ord': '256', 'convention': 'pascal', 'fn': 'GetDriverInfo', 'args': ['word', 'ptr']},
    {'ord': '257', 'convention': 'pascal', 'fn': 'GetNextDriver', 'args': ['word', 'long']},
    {'ord': '258', 'convention': 'pascal', 'fn': 'MapWindowPoints', 'args': ['word', 'word', 'ptr', 'word']},
    {'ord': '259', 'convention': 'pascal', 'fn': 'BeginDeferWindowPos', 'args': ['s_word']},
    {'ord': '260', 'convention': 'pascal', 'fn': 'DeferWindowPos', 'args': ['word', 'word', 'word', 's_word', 's_word', 's_word', 's_word', 'word']},
    {'ord': '261', 'convention': 'pascal', 'fn': 'EndDeferWindowPos', 'args': ['word']},
    {'ord': '262', 'convention': 'pascal', 'fn': 'GetWindow', 'args': ['word', 'word']},
    {'ord': '263', 'convention': 'pascal', 'fn': 'GetMenuItemCount', 'args': ['word']},
    {'ord': '264', 'convention': 'pascal', 'fn': 'GetMenuItemID', 'args': ['word', 'word']},
    {'ord': '265', 'convention': 'pascal', 'fn': 'ShowOwnedPopups', 'args': ['word', 'word']},
    {'ord': '266', 'convention': 'pascal', 'fn': 'SetMessageQueue', 'args': ['word']},
    {'ord': '267', 'convention': 'pascal', 'fn': 'ShowScrollBar', 'args': ['word', 'word', 'word']},
    {'ord': '268', 'convention': 'pascal', 'fn': 'GlobalAddAtom', 'args': ['str']},
    {'ord': '269', 'convention': 'pascal', 'fn': 'GlobalDeleteAtom', 'args': ['word']},
    {'ord': '270', 'convention': 'pascal', 'fn': 'GlobalFindAtom', 'args': ['str']},
    {'ord': '271', 'convention': 'pascal', 'fn': 'GlobalGetAtomName', 'args': ['word', 'ptr', 's_word']},
    {'ord': '272', 'convention': 'pascal', 'fn': 'IsZoomed', 'args': ['word']},
    {'ord': '273', 'convention': 'pascal', 'fn': 'ControlPanelInfo', 'args': ['word', 'word', 'str']},
    {'ord': '277', 'convention': 'pascal', 'fn': 'GetDlgCtrlID', 'args': ['word']},
    {'ord': '278', 'convention': 'pascal', 'fn': 'GetDesktopHwnd', 'args': []},
    {'ord': '279', 'convention': 'pascal', 'fn': 'OldSetDeskPattern', 'args': []},
    {'ord': '280', 'convention': 'pascal', 'fn': 'SetSystemMenu', 'args': ['word', 'word']},
    {'ord': '281', 'convention': 'pascal', 'fn': 'GetSysColorBrush', 'args': ['word']},
    {'ord': '282', 'convention': 'pascal', 'fn': 'SelectPalette', 'args': ['word', 'word', 'word']},
    {'ord': '283', 'convention': 'pascal', 'fn': 'RealizePalette', 'args': ['word']},
    {'ord': '284', 'convention': 'pascal', 'fn': 'GetFreeSystemResources', 'args': ['word']},
    {'ord': '285', 'convention': 'pascal', 'fn': 'SetDeskWallPaper', 'args': ['ptr']},
    {'ord': '286', 'convention': 'pascal', 'fn': 'GetDesktopWindow', 'args': []},
    {'ord': '287', 'convention': 'pascal', 'fn': 'GetLastActivePopup', 'args': ['word']},
    {'ord': '289', 'convention': 'pascal', 'fn': 'keybd_event', 'args': []},
    {'ord': '290', 'convention': 'pascal', 'fn': 'RedrawWindow', 'args': ['word', 'ptr', 'word', 'word']},
    {'ord': '292', 'convention': 'pascal', 'fn': 'UnhookWindowsHookEx', 'args': ['segptr']},
    {'ord': '294', 'convention': 'pascal', 'fn': 'LockWindowUpdate', 'args': ['word']},
    {'ord': '299', 'convention': 'pascal', 'fn': 'mouse_event', 'args': []},
    {'ord': '309', 'convention': 'pascal', 'fn': 'GetClipCursor', 'args': ['ptr']},
    {'ord': '314', 'convention': 'pascal', 'fn': 'SignalProc', 'args': ['word', 'word', 'word', 'word', 'word']},
    {'ord': '319', 'convention': 'pascal', 'fn': 'ScrollWindowEx', 'args': ['word', 's_word', 's_word', 'ptr', 'ptr', 'word', 'ptr', 'word']},
    {'ord': '324', 'convention': 'pascal', 'fn': 'FillWindow', 'args': ['word', 'word', 'word', 'word']},
    {'ord': '325', 'convention': 'pascal', 'fn': 'PaintRect', 'args': ['word', 'word', 'word', 'word', 'ptr']},
    {'ord': '326', 'convention': 'pascal', 'fn': 'GetControlBrush', 'args': ['word', 'word', 'word']},
    {'ord': '331', 'convention': 'pascal', 'fn': 'EnableHardwareInput', 'args': ['word']},
    {'ord': '332', 'convention': 'pascal', 'fn': 'UserYield', 'args': []},
    {'ord': '333', 'convention': 'pascal', 'fn': 'IsUserIdle', 'args': []},
    {'ord': '335', 'convention': 'pascal', 'fn': 'GetInputState', 'args': []},
    {'ord': '336', 'convention': 'pascal', 'fn': 'LoadCursorIconHandler', 'args': ['word', 'word', 'word']},
    {'ord': '356', 'convention': 'pascal', 'fn': 'LoadDIBCursorHandler', 'args': ['word', 'word', 'word']},
    {'ord': '357', 'convention': 'pascal', 'fn': 'LoadDIBIconHandler', 'args': ['word', 'word', 'word']},
    {'ord': '358', 'convention': 'pascal', 'fn': 'IsMenu', 'args': ['word']},
    {'ord': '359', 'convention': 'pascal', 'fn': 'GetDCEx', 'args': ['word', 'word', 'long']},
    {'ord': '362', 'convention': 'pascal', 'fn': 'DCHook', 'args': ['word', 'word', 'long', 'long']},
    {'ord': '364', 'convention': 'pascal', 'fn': 'LookupIconIdFromDirectoryEx', 'args': ['ptr', 'word', 'word', 'word', 'word']},
    {'ord': '368', 'convention': 'pascal', 'fn': 'CopyIcon', 'args': ['word', 'word']},
    {'ord': '369', 'convention': 'pascal', 'fn': 'CopyCursor', 'args': ['word', 'word']},
    {'ord': '370', 'convention': 'pascal', 'fn': 'GetWindowPlacement', 'args': ['word', 'ptr']},
    {'ord': '371', 'convention': 'pascal', 'fn': 'SetWindowPlacement', 'args': ['word', 'ptr']},
    {'ord': '373', 'convention': 'pascal', 'fn': 'SubtractRect', 'args': ['ptr', 'ptr', 'ptr']},
    {'ord': '374', 'convention': 'pascal', 'fn': 'DllEntryPoint', 'args': ['long', 'word', 'word', 'word', 'long', 'word']},
    {'ord': '384', 'convention': 'pascal', 'fn': 'SetMenuContextHelpId', 'args': ['word', 'word']},
    {'ord': '385', 'convention': 'pascal', 'fn': 'GetMenuContextHelpId', 'args': ['word']},
    {'ord': '390', 'convention': 'pascal', 'fn': 'CopyImage', 'args': ['word', 'word', 'word', 'word', 'word']},
    {'ord': '391', 'convention': 'pascal', 'fn': 'SignalProc32', 'args': ['long', 'long', 'long', 'word']},
    {'ord': '394', 'convention': 'pascal', 'fn': 'DrawIconEx', 'args': ['word', 'word', 'word', 'word', 'word', 'word', 'word', 'word', 'word']},
    {'ord': '395', 'convention': 'pascal', 'fn': 'GetIconInfo', 'args': ['word', 'ptr']},
    {'ord': '397', 'convention': 'pascal', 'fn': 'RegisterClassEx', 'args': ['ptr']},
    {'ord': '398', 'convention': 'pascal', 'fn': 'GetClassInfoEx', 'args': ['word', 'segstr', 'ptr']},
    {'ord': '399', 'convention': 'pascal', 'fn': 'ChildWindowFromPointEx', 'args': ['word', 'long', 'word']},
    {'ord': '400', 'convention': 'pascal', 'fn': 'FinalUserInit', 'args': []},
    {'ord': '402', 'convention': 'pascal', 'fn': 'GetPriorityClipboardFormat', 'args': ['ptr', 's_word']},
    {'ord': '403', 'convention': 'pascal', 'fn': 'UnregisterClass', 'args': ['str', 'word']},
    {'ord': '404', 'convention': 'pascal', 'fn': 'GetClassInfo', 'args': ['word', 'segstr', 'ptr']},
    {'ord': '406', 'convention': 'pascal', 'fn': 'CreateCursor', 'args': ['word', 'word', 'word', 'word', 'word', 'ptr', 'ptr']},
    {'ord': '407', 'convention': 'pascal', 'fn': 'CreateIcon', 'args': ['word', 'word', 'word', 'word', 'word', 'ptr', 'ptr']},
    {'ord': '408', 'convention': 'pascal', 'fn': 'CreateCursorIconIndirect', 'args': ['word', 'ptr', 'ptr', 'ptr']},
    {'ord': '409', 'convention': 'pascal', 'fn': 'InitThreadInput', 'args': ['word', 'word']},
    {'ord': '410', 'convention': 'pascal', 'fn': 'InsertMenu', 'args': ['word', 'word', 'word', 'word', 'segptr']},
    {'ord': '411', 'convention': 'pascal', 'fn': 'AppendMenu', 'args': ['word', 'word', 'word', 'segptr']},
    {'ord': '412', 'convention': 'pascal', 'fn': 'RemoveMenu', 'args': ['word', 'word', 'word']},
    {'ord': '413', 'convention': 'pascal', 'fn': 'DeleteMenu', 'args': ['word', 'word', 'word']},
    {'ord': '414', 'convention': 'pascal', 'fn': 'ModifyMenu', 'args': ['word', 'word', 'word', 'word', 'segptr']},
    {'ord': '415', 'convention': 'pascal', 'fn': 'CreatePopupMenu', 'args': []},
    {'ord': '416', 'convention': 'pascal', 'fn': 'TrackPopupMenu', 'args': ['word', 'word', 's_word', 's_word', 's_word', 'word', 'ptr']},
    {'ord': '418', 'convention': 'pascal', 'fn': 'SetMenuItemBitmaps', 'args': ['word', 'word', 'word', 'word', 'word']},
    {'ord': '420', 'convention': 'varargs', 'fn': '_wsprintf', 'args': ['ptr', 'str']},
    {'ord': '421', 'convention': 'pascal', 'fn': 'wvsprintf', 'args': ['ptr', 'str', 'ptr']},
    {'ord': '422', 'convention': 'pascal', 'fn': 'DlgDirSelectEx', 'args': ['word', 'ptr', 'word', 'word']},
    {'ord': '423', 'convention': 'pascal', 'fn': 'DlgDirSelectComboBoxEx', 'args': ['word', 'ptr', 'word', 'word']},
    {'ord': '427', 'convention': 'pascal', 'fn': 'FindWindowEx', 'args': ['word', 'word', 'str', 'str']},
    {'ord': '430', 'convention': 'pascal', 'fn': 'lstrcmp', 'args': ['str', 'str']},
    {'ord': '433', 'convention': 'pascal', 'fn': 'IsCharAlpha', 'args': ['word']},
    {'ord': '434', 'convention': 'pascal', 'fn': 'IsCharAlphaNumeric', 'args': ['word']},
    {'ord': '435', 'convention': 'pascal', 'fn': 'IsCharUpper', 'args': ['word']},
    {'ord': '436', 'convention': 'pascal', 'fn': 'IsCharLower', 'args': ['word']},
    {'ord': '437', 'convention': 'pascal', 'fn': 'AnsiUpperBuff', 'args': ['str', 'word']},
    {'ord': '438', 'convention': 'pascal', 'fn': 'AnsiLowerBuff', 'args': ['str', 'word']},
    {'ord': '441', 'convention': 'pascal', 'fn': 'InsertMenuItem', 'args': ['word', 'word', 'word', 'ptr']},
    {'ord': '448', 'convention': 'pascal', 'fn': 'DrawAnimatedRects', 'args': ['word', 'word', 'ptr', 'ptr']},
    {'ord': '449', 'convention': 'pascal', 'fn': 'DrawState', 'args': ['word', 'word', 'segptr', 'long', 'word', 's_word', 's_word', 's_word', 's_word', 'word']},
    {'ord': '450', 'convention': 'pascal', 'fn': 'CreateIconFromResourceEx', 'args': ['ptr', 'long', 'word', 'long', 'word', 'word', 'word']},
    {'ord': '451', 'convention': 'pascal', 'fn': 'TranslateMDISysAccel', 'args': ['word', 'ptr']},
    {'ord': '452', 'convention': 'pascal', 'fn': 'CreateWindowEx', 'args': ['long', 'str', 'str', 'long', 's_word', 's_word', 's_word', 's_word', 'word', 'word', 'word', 'segptr']},
    {'ord': '454', 'convention': 'pascal', 'fn': 'AdjustWindowRectEx', 'args': ['ptr', 'long', 'word', 'long']},
    {'ord': '455', 'convention': 'pascal', 'fn': 'GetIconID', 'args': ['word', 'long']},
    {'ord': '456', 'convention': 'pascal', 'fn': 'LoadIconHandler', 'args': ['word', 'word']},
    {'ord': '457', 'convention': 'pascal', 'fn': 'DestroyIcon', 'args': ['word']},
    {'ord': '458', 'convention': 'pascal', 'fn': 'DestroyCursor', 'args': ['word']},
    {'ord': '460', 'convention': 'pascal', 'fn': 'GetInternalWindowPos', 'args': ['word', 'ptr', 'ptr']},
    {'ord': '461', 'convention': 'pascal', 'fn': 'SetInternalWindowPos', 'args': ['word', 'word', 'ptr', 'ptr']},
    {'ord': '462', 'convention': 'pascal', 'fn': 'CalcChildScroll', 'args': ['word', 'word']},
    {'ord': '463', 'convention': 'pascal', 'fn': 'ScrollChildren', 'args': ['word', 'word', 'word', 'long']},
    {'ord': '465', 'convention': 'pascal', 'fn': 'DragDetect', 'args': ['word', 'long']},
    {'ord': '466', 'convention': 'pascal', 'fn': 'DrawFocusRect', 'args': ['word', 'ptr']},
    {'ord': '471', 'convention': 'pascal', 'fn': 'lstrcmpi', 'args': ['str', 'str']},
    {'ord': '475', 'convention': 'pascal', 'fn': 'SetScrollInfo', 'args': ['word', 's_word', 'ptr', 'word']},
    {'ord': '476', 'convention': 'pascal', 'fn': 'GetScrollInfo', 'args': ['word', 's_word', 'ptr']},
    {'ord': '477', 'convention': 'pascal', 'fn': 'GetKeyboardLayoutName', 'args': ['ptr']},
    {'ord': '482', 'convention': 'pascal', 'fn': 'EnableScrollBar', 'args': ['word', 'word', 'word']},
    {'ord': '483', 'convention': 'pascal', 'fn': 'SystemParametersInfo', 'args': ['word', 'word', 'ptr', 'word']},
    {'ord': '489', 'convention': 'pascal', 'fn': 'USER_489', 'args': []},
    {'ord': '490', 'convention': 'pascal', 'fn': 'USER_490', 'args': []},
    {'ord': '492', 'convention': 'pascal', 'fn': 'USER_492', 'args': []},
    {'ord': '496', 'convention': 'pascal', 'fn': 'USER_496', 'args': []},
    {'ord': '499', 'convention': 'pascal', 'fn': 'WNetErrorText', 'args': ['word', 'ptr', 'word']},
    {'ord': '501', 'convention': 'pascal', 'fn': 'WNetOpenJob', 'args': ['ptr', 'ptr', 'word', 'ptr']},
    {'ord': '502', 'convention': 'pascal', 'fn': 'WNetCloseJob', 'args': ['word', 'ptr', 'ptr']},
    {'ord': '503', 'convention': 'pascal', 'fn': 'WNetAbortJob', 'args': ['ptr', 'word']},
    {'ord': '504', 'convention': 'pascal', 'fn': 'WNetHoldJob', 'args': ['ptr', 'word']},
    {'ord': '505', 'convention': 'pascal', 'fn': 'WNetReleaseJob', 'args': ['ptr', 'word']},
    {'ord': '506', 'convention': 'pascal', 'fn': 'WNetCancelJob', 'args': ['ptr', 'word']},
    {'ord': '507', 'convention': 'pascal', 'fn': 'WNetSetJobCopies', 'args': ['ptr', 'word', 'word']},
    {'ord': '508', 'convention': 'pascal', 'fn': 'WNetWatchQueue', 'args': ['word', 'ptr', 'ptr', 'word']},
    {'ord': '509', 'convention': 'pascal', 'fn': 'WNetUnwatchQueue', 'args': ['str']},
    {'ord': '510', 'convention': 'pascal', 'fn': 'WNetLockQueueData', 'args': ['ptr', 'ptr', 'ptr']},
    {'ord': '511', 'convention': 'pascal', 'fn': 'WNetUnlockQueueData', 'args': ['ptr']},
    {'ord': '512', 'convention': 'pascal', 'fn': 'WNetGetConnection', 'args': ['ptr', 'ptr', 'ptr']},
    {'ord': '513', 'convention': 'pascal', 'fn': 'WNetGetCaps', 'args': ['word']},
    {'ord': '514', 'convention': 'pascal', 'fn': 'WNetDeviceMode', 'args': ['word']},
    {'ord': '515', 'convention': 'pascal', 'fn': 'WNetBrowseDialog', 'args': ['word', 'word', 'ptr']},
    {'ord': '516', 'convention': 'pascal', 'fn': 'WNetGetUser', 'args': ['ptr', 'ptr']},
    {'ord': '517', 'convention': 'pascal', 'fn': 'WNetAddConnection', 'args': ['str', 'str', 'str']},
    {'ord': '518', 'convention': 'pascal', 'fn': 'WNetCancelConnection', 'args': ['str', 'word']},
    {'ord': '519', 'convention': 'pascal', 'fn': 'WNetGetError', 'args': ['ptr']},
    {'ord': '520', 'convention': 'pascal', 'fn': 'WNetGetErrorText', 'args': ['word', 'ptr', 'ptr']},
    {'ord': '523', 'convention': 'pascal', 'fn': 'WNetRestoreConnection', 'args': ['word', 'ptr']},
    {'ord': '524', 'convention': 'pascal', 'fn': 'WNetWriteJob', 'args': ['word', 'ptr', 'ptr']},
    {'ord': '525', 'convention': 'pascal', 'fn': 'WNetConnectDialog', 'args': ['word', 'word']},
    {'ord': '526', 'convention': 'pascal', 'fn': 'WNetDisconnectDialog', 'args': ['word', 'word']},
    {'ord': '527', 'convention': 'pascal', 'fn': 'WNetConnectionDialog', 'args': ['word', 'word']},
    {'ord': '528', 'convention': 'pascal', 'fn': 'WNetViewQueueDialog', 'args': ['word', 'ptr']},
    {'ord': '529', 'convention': 'pascal', 'fn': 'WNetPropertyDialog', 'args': ['word', 'word', 'word', 'str', 'word']},
    {'ord': '530', 'convention': 'pascal', 'fn': 'WNetGetDirectoryType', 'args': ['ptr', 'ptr']},
    {'ord': '531', 'convention': 'pascal', 'fn': 'WNetDirectoryNotify', 'args': ['word', 'ptr', 'word']},
    {'ord': '532', 'convention': 'pascal', 'fn': 'WNetGetPropertyText', 'args': ['word', 'word', 'str', 'str', 'word', 'word']},
    {'ord': '600', 'convention': 'pascal', 'fn': 'GetShellWindow', 'args': []},
    {'ord': '606', 'convention': 'pascal', 'fn': 'FormatMessage', 'args': ['long', 'segptr', 'word', 'word', 'ptr', 'word', 'ptr']},
    {'ord': '608', 'convention': 'pascal', 'fn': 'GetForegroundWindow', 'args': []},
    {'ord': '609', 'convention': 'pascal', 'fn': 'SetForegroundWindow', 'args': ['word']},
    {'ord': '610', 'convention': 'pascal', 'fn': 'DestroyIcon32', 'args': ['word', 'word']},
    {'ord': '621', 'convention': 'pascal', 'fn': 'EnumDisplaySettings', 'args': ['str', 'long', 'ptr']},
    {'ord': '656', 'convention': 'pascal', 'fn': 'DrawFrameControl', 'args': ['word', 'ptr', 'word', 'word']},
    {'ord': '657', 'convention': 'pascal', 'fn': 'DrawCaptionTemp', 'args': ['word', 'word', 'ptr', 'word', 'word', 'ptr', 'word']},
    {'ord': '659', 'convention': 'pascal', 'fn': 'DrawEdge', 'args': ['word', 'ptr', 'word', 'word']},
    {'ord': '660', 'convention': 'pascal', 'fn': 'DrawCaption', 'args': ['word', 'word', 'ptr', 'word']},
    {'ord': '665', 'convention': 'pascal', 'fn': 'GetMenuItemRect', 'args': ['word', 'word', 'word', 'ptr']},
    {'ord': '666', 'convention': 'pascal', 'fn': 'CheckMenuRadioItem', 'args': ['word', 'word', 'word', 'word', 'word']},
    {'ord': '668', 'convention': 'pascal', 'fn': 'SetWindowRgn', 'args': ['word', 'word', 'word']},
    {'ord': '819', 'convention': 'pascal', 'fn': 'PeekMessage32', 'args': ['ptr', 'word', 'word', 'word', 'word', 'word']},
    {'ord': '821', 'convention': 'pascal', 'fn': 'TranslateMessage32', 'args': ['ptr', 'word']},
    {'ord': '823', 'convention': 'pascal', 'fn': 'CallMsgFilter32', 'args': ['ptr', 'word', 'word']},
    {'ord': '827', 'convention': 'pascal', 'fn': 'MessageBoxIndirect', 'args': ['ptr']},
    {'ord': '902', 'convention': 'pascal', 'fn': 'LoadSystemLanguageString', 'args': ['word', 'word', 'ptr', 'word', 'word']},
    {'ord': '905', 'convention': 'pascal', 'fn': 'ChangeDialogTemplate', 'args': []},
    {'ord': '906', 'convention': 'pascal', 'fn': 'GetNumLanguages', 'args': []},
    {'ord': '907', 'convention': 'pascal', 'fn': 'GetLanguageName', 'args': ['word', 'word', 'ptr', 'word']},
    {'ord': '909', 'convention': 'pascal', 'fn': 'SetWindowTextEx', 'args': ['word', 'str', 'word']},
    {'ord': '910', 'convention': 'pascal', 'fn': 'BiDiMessageBoxEx', 'args': []},
    {'ord': '911', 'convention': 'pascal', 'fn': 'SetDlgItemTextEx', 'args': ['word', 'word', 'str', 'word']},
    {'ord': '913', 'convention': 'pascal', 'fn': 'GetCodePageSystemFont', 'args': ['word', 'word']},
    {'ord': '914', 'convention': 'pascal', 'fn': 'QueryCodePage', 'args': ['word', 'word', 'word', 'long']},
    {'ord': '916', 'convention': 'pascal', 'fn': 'CreateDialogIndirectParamML', 'args': ['word', 'ptr', 'word', 'ptr', 'long', 'word', 'word', 'str', 'word']},
    {'ord': '918', 'convention': 'pascal', 'fn': 'DialogBoxIndirectParamML', 'args': ['word', 'word', 'word', 'ptr', 'long', 'word', 'word', 'str', 'word']},
    {'ord': '919', 'convention': 'pascal', 'fn': 'LoadLanguageString', 'args': ['word', 'word', 'word', 'ptr', 'word']},
    {'ord': '923', 'convention': 'pascal', 'fn': 'FindLanguageResource', 'args': ['word', 'str', 'str', 'word']},
    {'ord': '930', 'convention': 'pascal', 'fn': 'MessageBoxEx', 'args': ['word', 'str', 'str', 'word', 'word']},
    {'ord': '1000', 'convention': 'pascal', 'fn': 'SetProcessDefaultLayout', 'args': ['long']},
    {'ord': '1001', 'convention': 'pascal', 'fn': 'GetProcessDefaultLayout', 'args': ['ptr']},
]